######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 18 11:32:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h render.h
SOURCES += main.cpp mainwindow.cpp render.cpp
