######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 15 10:48:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h render.h
SOURCES += main.cpp mainwindow.cpp render.cpp
