######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 27 09:43:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += render.h
SOURCES += main.cpp render.cpp
